name: vd-bot

services:
  app:
    build:
      context: .
    container_name: vd_rag_bot_app
    command:
      - uv
      - run
      - uvicorn
      - app.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --reload
    env_file:
      - .env
    environment:
      # Leave DATABASE_URL empty by default since we're removing Postgres from this stack.
      # If your app *requires* it, set an external DB in .env, e.g. a managed Postgres.
      DATABASE_URL: ${DATABASE_URL:-}
      CHATWOOT_BOT_ACCESS_TOKEN: ${CHATWOOT_BOT_ACCESS_TOKEN:-nS7yBjTg66L29cSUVypLQnGB}
      CHATWOOT_API_URL: ${CHATWOOT_API_URL:-http://localhost:3000/api/v1}
      # If your bot calls n8n webhooks, expose the base here for convenience:
      N8N_BASE_URL: ${N8N_BASE_URL:-http://localhost:5678}
    ports:
      - "8080:8080"
    volumes:
      - .:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
    # No DB dependency anymore
    depends_on: []

  n8n:
    image: n8nio/n8n:latest
    container_name: vd_n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    env_file:
      - .env
    environment:
      # Editor/UI URL
      N8N_EDITOR_BASE_URL: ${N8N_EDITOR_BASE_URL:-http://localhost:5678}
      # Host/port inside container
      N8N_HOST: ${N8N_HOST:-localhost}
      N8N_PORT: 5678
      # Public URL where webhooks will be reached (adjust for your domain in prod)
      WEBHOOK_URL: ${WEBHOOK_URL:-http://localhost:5678}
      N8N_SECURE_COOKIE: "false"
      GENERIC_TIMEZONE: ${GENERIC_TIMEZONE:-America/Argentina/Buenos_Aires}
      # Optional auth for the editor (uncomment to protect in dev/prod)
      # N8N_BASIC_AUTH_ACTIVE: "true"
      # N8N_BASIC_AUTH_USER: ${N8N_BASIC_AUTH_USER:-admin}
      # N8N_BASIC_AUTH_PASSWORD: ${N8N_BASIC_AUTH_PASSWORD:-change-me}
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
